name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        lz4: ['1.9.2']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install lz4
      run: |
        set -xe
        BUILD_DIR="/tmp/build/lz4"
        mkdir -p "$BUILD_DIR"
        curl -sL https://github.com/lz4/lz4/archive/refs/tags/v${{ matrix.lz4}}.tar.gz | \
          tar -zx --strip-components=1 -C "$BUILD_DIR"
        cd "$BUILD_DIR"
        make
        sudo make install
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Phpize
      run: phpize
    - name: Configure
      run: ./configure
    - name: Make
      run: make
    - name: Make test
      run: make test
