name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install lz4
      run: sudo apt-get install -y liblz4-dev
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Configure
      run: ./configure
    - name: Make
      run: make
    - name: Make test
      run: make test
