name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        php: ['8.1', '8.2', '8.3', '8.4']
        lz4: ['1.9.2', '1.10.0']

    name: ${{ matrix.os }} - PHP ${{ matrix.php }} - lz4 ${{ matrix.lz4 }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install lz4
      run: |
        set -xe
        BUILD_DIR="/tmp/build/lz4"
        mkdir -p "$BUILD_DIR"
        curl -sL https://github.com/lz4/lz4/archive/refs/tags/v${{ matrix.lz4}}.tar.gz | \
          tar -zx --strip-components=1 -C "$BUILD_DIR"
        cd "$BUILD_DIR"
        make
        sudo make install
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - name: Phpize
      run: phpize
    - name: Configure
      run: ./configure
    - name: Make
      run: make
    - name: Make test
      run: make test

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3.10']
        lz4: ['1.10.0']

    name: windows latest - PHP ${{ matrix.php }} - lz4 ${{ matrix.lz4 }}
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4
    - name: Download LZ4 Windows Binary Package
      run: |
        $ErrorActionPreference = 'Stop'
        $Lz4Directory = "C:\lz4"
        $Lz4Zip = "lz4.zip"
        $Lz4Version = "${{ matrix.lz4 }}"
        $Lz4VersionUnderscored = $Lz4Version -replace '\.','_'
        New-Item -ItemType Directory -Force -Path $Lz4Directory
        Invoke-WebRequest -Uri "https://github.com/lz4/lz4/releases/download/v$Lz4Version/lz4_win64_v$Lz4VersionUnderscored.zip" -OutFile $Lz4Zip
        Expand-Archive -Path $Lz4Zip -DestinationPath $Lz4Directory -Force
    - name: Setup PHP
      run: |
        Invoke-WebRequest -Uri https://windows.php.net/downloads/releases/php-${{ matrix.php }}-nts-Win32-vs16-x64.zip -OutFile php.zip
        Expand-Archive -Path php.zip -DestinationPath C:\php
        [System.Environment]::SetEnvironmentVariable('Path', "C:\php\php-${{ matrix.php }}-nts-Win32-vs16-x64;$Env:Path", [System.EnvironmentVariableTarget]::Machine)
    - name: Setup PHP Development Package
      run: |
        Invoke-WebRequest -Uri https://windows.php.net/downloads/releases/php-devel-pack-${{ matrix.php }}-nts-Win32-vs16-x64.zip -OutFile php-devel-pack.zip
        Expand-Archive -Path php-devel-pack.zip -DestinationPath C:\php-devel-pack
        [System.Environment]::SetEnvironmentVariable('Path', "C:\php-devel-pack\php-${{ matrix.php }}-devel-vs16-x64;$Env:Path", [System.EnvironmentVariableTarget]::Machine)
    - name: Setup PHP SDK
      run: |
        Invoke-WebRequest -Uri https://github.com/php/php-sdk-binary-tools/archive/refs/tags/php-sdk-2.3.0.zip -OutFile php-sdk.zip
        Expand-Archive -Path php-sdk.zip -DestinationPath C:\php-sdk
        [System.Environment]::SetEnvironmentVariable('Path', "C:\php-sdk\php-sdk-binary-tools-php-sdk-2.3.0;$Env:Path", [System.EnvironmentVariableTarget]::Machine)
    - name: Invoke the Starter Script
      run: C:\php-sdk\phpsdk-vs17-x64.bat
    - name: Phpize
      run: phpize
    - name: Configure
      run: configure --with-lz4="C:\lz4"
    - name: Make
      run: nmake
    - name: Make test
      run: nmake test
