name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install lz4
      run: sudo apt-get install -y liblz4-dev
    - name: Setup PHP
      uses: shivammathur/setup-php@2
      with:
        php-version: '8.3'
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
